apiVersion: v2
name: nominatim
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

maintainers:
  - email: me@godwin.dev
    name: radioActive DROID

dependencies:
  - name: common
    version: 1.x.x
    repository: https://charts.bitnami.com/bitnami
  - name: postgresql
    version: 11.6.20
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled

annotations:
  repository: gpproton/helm-charts
